### ISSUE TITLE
should iPhoneFramework.sh work from the command line?

### ISSUE THREAD

**Issue by cricketgeek** [gabriel/yajl-objc#14]
When I run the iPhoneFramework.sh I get:
lipo: can't open input file: build/Release-iphoneos/libYAJLIOSDevice.a (No such file or directory)

There is a something existing under Example/TestApp/Frameworks, is that useful per the README instructions? I've also tried using the most recent release of the download and I can get that to seemingly build in a test Xcode 4.01 project but then can't import any of the headers in my example class.

I can run the test project from the cloned repo, just can't get it working in another project.

**Comment by gabriel** [comment]
Released new pod as YAJLO. See new README.
