### ISSUE TITLE
is "CombineLibs.sh" necessary in the Makefile anymore?

### ISSUE THREAD

**Issue by skydivedan** [gabriel/yajl-objc#18]
In the makefile, the "default" build executes both "CombineLibs.sh" and "iPhoneFramework.sh". Both of these scripts run "lipo" to combine the Simulator & Device builds. Couldn't we make the output of "CombineLibs" the path of the lipo'd library, and pipe it into iPhoneFramework.sh? Or just not have "CombineLibs.sh" in the build process at all?

Or, am I just misunderstanding something about the build process?

**Comment by gabriel** [comment]
Released new pod as YAJLO. See new README.
