### ISSUE TITLE
Xcode 4 (IOS) Install - clarification on "Other Linker Flags"

### ISSUE THREAD

**Issue by ethanhall** [gabriel/yajl-objc#22]
Gabriel,

Thanks for putting together this nice framework.  I'm running Xcode 4.2.  Under my "Other Linker Flags" in Build Settings fro my target, I have two entries: "Debug" and "Release".  I am unable to add the instructed parameters "-ObjC" and "all_load" as I can only add one on "Debug" and one on Release".

Please advise on how I should address this for proper functionality.

Thanks and regards,
Ethan

**Comment by gabriel** [comment]
Released new pod as YAJLO. See new README.
