### ISSUE TITLE
'yajl/yajl_common.h' file not found

### ISSUE THREAD

**Issue by kilianc** [gabriel/yajl-objc#27]
I get this, any help?

```
/Volumes/WS/xxx/Frameworks/YAJL.framework/Headers/yajl_parse.h:38:10: 'yajl/yajl_common.h' file not found
```

Using XCode 4

**Comment by herau** [comment]
i have the same error when i define `yajl` as pod spec dependency 

` NOTE  | [iOS] xcodebuild:  yajl/src/yajl_alloc.h:42:10: fatal error: 'api/yajl_common.h' file not found`

**Comment by herau** [comment]
@kilianc do you have solved you issue ?

**Comment by gabriel** [comment]
Released new pod as YAJLO. See new README.
