### ISSUE TITLE
Yajl is not working in Xcode 5

### ISSUE THREAD

**Issue by BhartiBhavya** [gabriel/yajl-objc#36]
Could you please update Yajl for Xcode 5?
I tried linking yajl in xcode 5.1 but it is giving me the exception "'NSInvalidArgumentException', reason: '-[__NSCFConstantString yajl_JSON]: unrecognized selector sent to instance".
I would like to mention that in simulators, it work fine.

**Comment by gabriel** [comment]
Released new pod as YAJLO. See new README.
