### ISSUE TITLE
Compile errors in iPhone libs

### ISSUE THREAD

**Issue by eagereyes** [gabriel/yajl-objc#4]
I'm getting weird errors when trying to compile the iPhone project. It's showing these as two errors and one warning each, all with identical messages. I'm using the latest (non-beta) SDK.

YAJLDocument.m:88: warning: '-document:didAddObject:toArray:' not found in protocol(s)
YAJLDocument.m:94: warning: '-document:didSetObject:forKey:inDictionary:' not found in protocol(s)
YAJLDocument.m:128: warning: '-document:didAddDictionary:' not found in protocol(s)
YAJLDocument.m:147: warning: '-document:didAddArray:' not found in protocol(s)

The functions are defined in the protocol, I have no idea what it's complaining about. Any ideas?

**Comment by gabriel** [comment]
Released new pod as YAJLO. See new README.
