### ISSUE TITLE
__weak issue

### ISSUE THREAD

**Issue by RayzorDragon** [gabriel/yajl-objc#42]
Recently I've been having problems with dict_, array_, and key_ in YAJLDocument.h. They're all marked as __weak but ARC is disabled as per warnings I'm getting from pod linting my own pod that uses yajl-objc as a dependency. My problems vanish when I remove the '__weak' from each of this variables. Are there plans to update this repo to account for this bug?

**Comment by gabriel** [comment]
Released new pod as YAJLO. See new README.
