### ISSUE TITLE
Build failed with pod lib lint when yajl-obj dependency

### ISSUE THREAD

**Issue by herau** [gabriel/yajl-objc#45]
Hello,

I'm trying to create a CocoaPod lib. My Project has a dependency on `yajl-obj` and this dependency doesn't compile during `pod lib lint` step.

I have created a [stackoverflow question](http://stackoverflow.com/questions/42067614/cocoapods-spec-lint-build-failed-with-yajl-dependency) about this subject.

Do you have any idea about this issue ? 

> The yajl project seems to be no maintained anymore, so i prefer not create an issue on that repo.

**Comment by gabriel** [comment]
Released new pod as `YAJLO`. See new README.
